### ISSUE TITLE
Bug Report: Scan update too slow, enemies not listed properly.

### ISSUE THREAD

**Issue by FireGeneral** [ManindraDeMel/LethalCompanyEnemyScan#1]
Hi! After playing some rounds with your mod, I found some issues with your mod.

1. Enemies not listed properly:
I've encountered situation where there's a hoarding bug on the map, and your mod never registered it as an enemy throughout the entire round.
Note: Not just hoarding bug, it also happened to Roaming Locusts and Circuit Bees.

2. Enemies list update too slow:
This issue becomes quite glaring in later map. To give you an example: There're three thumpers spawned throughout the map but at different time. Your mod failed to register any of those thumpers in time. It's only after we've killed all of them, your mod started to register and display them "one by one", which was over 10 minutes too late.

I think the Enemy Scan need to register the monster as soon as they're spawned, which leads to another mod which only scans and provides number for the amounts of enemies on the map. (Mom_Llama-Lethal_Company_Enhancer) I've tested your mod alongside with that one, and that one is able to detect and register all monsters on the map almost instant.
English not my native, thank you!

**Comment by ManindraDeMel** [comment]
Hi, thanks for creating this issue. Ill have a look in the next two or so days and publish a patch

**Comment by ManindraDeMel** [comment]
How the list refreshes is it scans the whole map for EnemyAI objects and this happens every hour (when enemies are spawned). However maybe i missed something so ill have a look

**Comment by FireGeneral** [comment]
> How the list refreshes is it scans the whole map for EnemyAI objects and this happens every hour (when enemies are spawned). However maybe i missed something so ill have a look

Thank you for replying.
First off, enemies can spawn between hours. For example: Enemies can spawn at random time, say 8:21am, which is soon after landing on the moon, causing the scan to fail.
Also, I couldn't see your mod update every hour (After using your mod for more than 10 hours, I can say your mod most consistently update its list around 10am and 12am)

**Comment by ManindraDeMel** [comment]
> > How the list refreshes is it scans the whole map for EnemyAI objects and this happens every hour (when enemies are spawned). However maybe i missed something so ill have a look
> 
> Thank you for replying.
> First off, enemies can spawn between hours. For example: Enemies can spawn at random time, say 8:21am, which is soon after landing on the moon, causing the scan to fail.
> Also, I couldn't see your mod update every hour (After using your mod for more than 10 hours, I can say your mod most consistently update its list around 10am and 12am)

Ok ill patch it now

**Comment by ManindraDeMel** [comment]
Please test now! Thanks for submitting this issue. Let me know if there are any other problems as I don't have an a lot of spare of time right now to thoroughly play the game :)
