### ISSUE TITLE
Only host can scan

### ISSUE THREAD

**Issue by bigbeau** [ManindraDeMel/LethalCompanyEnemyScan#3]
Playing with some friends, we discovered that nobody except the host can use the enemyscan command. For anyone that isn't hosting, the command returns the no enemies in space error. This was consistent regardless of who hosted.

**Comment by ManindraDeMel** [comment]
Hi, thats pretty interesting i might rollback for now just so i can test

**Comment by ManindraDeMel** [comment]
Thanks for making this, ill have a look

**Comment by ManindraDeMel** [comment]
> Playing with some friends, we discovered that nobody except the host can use the enemyscan command. For anyone that isn't hosting, the command returns the no enemies in space error. This was consistent regardless of who hosted. 

Do you remember if this is only present in the newest version?

**Comment by bigbeau** [comment]
This was present on 1.0.1 (when I played yesterday), haven't had a chance to check the most recent version yet. We all had the same version of the mod installed too, so there wasnt an issue with one person missing it or having a different version.

**Comment by ManindraDeMel** [comment]
Yeah okay, ill have a look. But I'm thinking its something to do with TerminalAPI rather than my mod

**Comment by ManindraDeMel** [comment]
Yep I can confirm this only works for the host right now (on the latest version too)

**Comment by bigbeau** [comment]
> Yeah okay, ill have a look. But I'm thinking its something to do with TerminalAPI rather than my mod

so is there anything that can be done about this on your side or is it pretty much just up to TerminalAPI to update for multiplayer compatibility? (assuming the bug is theirs)

**Comment by ManindraDeMel** [comment]
> > Yeah okay, ill have a look. But I'm thinking its something to do with TerminalAPI rather than my mod
> 
> so is there anything that can be done about this on your side or is it pretty much just up to TerminalAPI to update for multiplayer compatibility? (assuming the bug is theirs)

Ill have a look and talk to the creator of TerminalAPI too. This may take a while so just hang on for a bit :)

**Comment by bigbeau** [comment]
No worries! And thanks for making this mod in the first place :)

**Comment by ManindraDeMel** [comment]
Hi could you now test this with your friends?

**Comment by ManindraDeMel** [comment]
Will mark this as resolved. Been tested by me and another dev

**Comment by bigbeau** [comment]
Awesome. Never got notif for your message the other day, my apologies. Glad to know it works now!!
