### ISSUE TITLE
Bug Report: Game lag as Terminal Api constantly check the list

### ISSUE THREAD

**Issue by FireGeneral** [ManindraDeMel/LethalCompanyEnemyScan#4]
Following Issue #1 

After using the newest version of your mod (v1.1.0) for more than 10 rounds, I found the game become laggier than before.
The culprit:
![螢幕擷取畫面 2023-12-08 053500](https://github.com/ManindraDeMel/LethalCompanyEnemyScan/assets/82710934/228c7089-396e-4aff-80c6-a87d38c4f81c)

As you switched to RoundManager's Update method, terminal API now updates its list all the time, not only causing bloated log file, but also game lag.

I understand it's for the sake of being able to scan and update the list immediately after a new monster is spawned on the moon, but I believe this should be optimized. Perhaps adjusting the frequency so it doesn't check all the time but still frequent enough that one doesn't need to wait almost a minute to get an updated list? Or perhaps the lag is actually caused by the Terminal API?

**Comment by ManindraDeMel** [comment]
> Following Issue #1 
> 
> After using the newest version of your mod (v1.1.0) for more than 10 rounds, I found the game become laggier than before.
> The culprit:
> ![螢幕擷取畫面 2023-12-08 053500](https://github.com/ManindraDeMel/LethalCompanyEnemyScan/assets/82710934/228c7089-396e-4aff-80c6-a87d38c4f81c)
> 
> As you switched to RoundManager's Update method, terminal API now updates its list all the time, not only causing bloated log file, but also game lag.
> 
> I understand it's for the sake of being able to scan and update the list immediately after a new monster is spawned on the moon, but I believe this should be optimized. Perhaps adjusting the frequency so it doesn't check all the time but still frequent enough that one doesn't need to wait almost a minute to get an updated list? Or perhaps the lag is actually caused by the Terminal API?

Hi thanks for making this issue. Yeah in the most recent update its called every update method and it is bloating the log file but ill try find another fix

**Comment by ManindraDeMel** [comment]
Ive added a hotfix to the mod. Please have a look when you have time :)
Again, thanks for testing this stuff for me
